# Generated by Django 3.1 on 2020-08-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('market', models.CharField(choices=[('PL', 'Poland'), ('DE', 'Germany'), ('UA', 'Ukraine'), ('FR', 'France')], max_length=2)),
                ('account_number', models.CharField(max_length=26)),
                ('risk_level', models.CharField(choices=[('L', 'LOW'), ('M', 'Medium'), ('H', 'High')], max_length=1)),
                ('offer_consent', models.BooleanField()),
                ('automatic_consent', models.BooleanField()),
            ],
        ),
    ]
