# Generated by Django 3.1 on 2020-08-11 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200810_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('task_name', models.CharField(max_length=50)),
                ('task_status', models.IntegerField(choices=[(0, 'Prepared'), (1, 'Scheduled'), (2, 'Initiated'), (3, 'Pending'), (4, 'Done')], default=0)),
                ('task_json', models.TextField()),
                ('task_annotations', models.CharField(max_length=250)),
                ('task_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('payment_title', models.CharField(max_length=300)),
                ('payment_status', models.IntegerField(choices=[(0, 'Notaccepted'), (1, 'Accepted'), (2, 'Removed')])),
                ('payment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer')),
            ],
        ),
    ]
