# Generated by Django 3.1 on 2020-08-11 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_payment_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_annotations',
            new_name='annotations',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_json',
            new_name='json',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_user',
            new_name='user',
        ),
    ]
